services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
    networks:
      - app-network

networks:
  app-network:
    external: true
