services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - app-network
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  jenkins_home:
